scss_files: "app/assets/stylesheets/**/*.scss"

linters:
  HexLength:
    enabled: true
    style: short
    exclude:
      - "app/assets/stylesheets/_colors.scss"

  HexNotation:
    enabled: true
    style: uppercase

  IdSelector:
    enabled: false

  LeadingZero:
    enabled: true
    style: include_zero

  NestingDepth:
    enabled: true
    max_depth: 4
    ignore_parent_selectors: false

  PropertySortOrder:
    enabled: true
    exclude:
      - "app/assets/stylesheets/_reset.scss"
    order:
      - position
      - top
      - right
      - bottom
      - left
      - background
      - background-image
      - background-size
      - background-repeat
      - color
      - width
      - max-width
      - min-width
      - height
      - max-height
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - border
      - border-color
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-collapse
      - border-radius
      - outline
      - font
      - font-size
      - font-family
      - font-weight
      - font-style
      - line-height
      - letter-spacing
      - text-align
      - text-decoration
      - text-shadow
      - text-transform
      - box-shadow
      - display
      - float
      - opacity
      - vertical-align
      - justify-content
      - grid-area
      - grid-template-rows
      - grid-template-columns
      - grid-template-areas

  SelectorDepth:
    enabled: true
    max_depth: 4

  SelectorFormat:
    enabled: true
    ignored_names:
      - field_with_errors
      - field_with_message

  SingleLinePerSelector:
    enabled: true
    exclude:
      - "app/assets/stylesheets/_reset.scss"

  StringQuotes:
    enabled: true
    style: double_quotes
