# This is the actual configuration file for litestream.
#
# You can either use the generated `config/initializers/litestream.rb` file to
# configure the litestream-ruby gem, which will populate these ENV variables
# when using the `rails litestream:replicate` command.
#
# Or, if you prefer, manually manage ENV variables and this configuration file.
# In that case, simply ensure that the ENV variables are set before running the
# `replicate` command.
#
# For more details, see: https://litestream.io/reference/config/
access-key-id: $LITESTREAM_ACCESS_KEY_ID
secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY

dbs:
  - path: storage/production.sqlite3
    replicas:
      - url: s3://$LITESTREAM_REPLICA_HOST/untitled/storage/production.sqlite3
