name: CD

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_call:

jobs:
  Build:
    uses: ./.github/workflows/ci.yml

  Deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: Build
    concurrency:
      group: cd-production
    env:
      DESTINATION: production
    permissions:
      packages: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Ruby
        uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          bundler-cache: true

      - name: Start the SSH agent
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Deploy the application
        shell: bash
        env:
          ${{ insert }}: ${{ secrets }}
          DOCKER_BUILDKIT: 1
        run: bin/kamal deploy --destination=$DESTINATION

      - name: Release the Kamal lock, if needed
        shell: bash
        if: ${{ cancelled() || failure() }}
        run: bin/kamal lock release --destination=$DESTINATION
